### ISSUE TITLE
Texto parece estar em padrão que não reconhece acentos

### ISSUE THREAD

**Issue by lopesl** [Pedro-Thales/SentiWordNet-PT-BR#1]
Olá!

Muito bom esse trabalho! Contudo, o texto parece  em um padrão que não reconhece acentos e diacríticos do português. Confira como ele está:

# A primeira coluna corresponde ao ID baseado na identificaÁ„o
# 	internacional baseada no WordNet 3.0.
# Os valores PosPont e NegPont s„o respectivamente a pontuaÁ„o 
# 	positiva e negativa dos termos.
#
# A identaÁ„o padr„o utiliza tabulaÁ„o entre as colunas.

Até!

l.

**Comment by Pedro-Thales** [comment]
Olá, obrigado pelo comentário, mas acho que o problema é o preview do arquivo raw do Github.

Baixando o arquivo e abrindo pelo Notepad++ por exemplo você não vai ter esse problema.

Abraço.

Ps. No bloco de notas do windows também abre normalmente sem os problemas de "encoding".
