### ISSUE TITLE
Uso em trabalhos acadêmicos

### ISSUE THREAD

**Issue by ReniDelonzek** [Pedro-Thales/SentiWordNet-PT-BR#3]
Olá @Pedro-Thales, gostaria de parabeniza-lo pelo excelente trabalho neste projeto!

Estou construindo um algoritmo de análise de sentimentos, e estou avaliando utilizar o dicionário construído para parte da análise. Gostaria de saber se existe permissão sua para tal, e como eu poderia referenciar este projeto no meu trabalho.

Grato pela atenção, abraço!

**Comment by Pedro-Thales** [comment]
Sem problemas! Pode usar a vontade. Pode referenciar colocando o link para esse repositório.

A licença que coloquei nesse repositório permite quaisquer tipos de uso.

**Comment by ReniDelonzek** [comment]
Muito obrigado!
